### ISSUE TITLE
1.9 Loop cast bullets do not loop.

### ISSUE THREAD

**Issue by NolanSyKinsley** [Vazkii/Psi#160]
I think this is a bug, unless something major changed since Dire's Spotlight. I copied Dire's wall spell to ensure I had a working code: http://i.imgur.com/RPPVp1W.png Then place the spell on a loop cast bullet and fire. The first column is built, but the spell does not loop.
MC 1.9 forge #1804

**Comment by yrsegal** [comment]
That spell doesn't work for me at all, even manually setting the loop index. Could you try a different loopcast spell?

**Comment by mwchase** [comment]
I seem to be seeing this again. Posting this as a comment because it seems like the same kind of symptom.

Using AutoRegLib-1.1-4, Psi r1.1-44, Forge 1.11.2-13.20.0.2224 (and I think I didn't uncheck the mercurius thing, so that's there as well) under Java 8.

FML log: http://pastebin.com/cVyfQWyC

In a world with more mods installed, I reached the loopcast tutorial legitimately, tried it out, and it never looped. Specifically:

I made a basic spell that output the loopcast index with the debug trick. It only ever output 0.0.

I then made this minimal setup. Constructed various permutations of CAD, loaded the debug spell into a loopcast bullet, and cast it. It only ever fires once.

I just now thought to try with a spell circle bullet. That output 0.0 through 19.0, so looping itself, and the loopcast index selector, work.

Spell, for reference: http://imgur.com/a/xiFge

Is there anything I need to do differently to make the loopcast happen, or should just using the CAD with the loopcast bullet selected be sufficient? It's sufficient for the spell circle.
