### ISSUE TITLE
Not breaking blocks with a Ivory CAD

### ISSUE THREAD

**Issue by lokkenpa** [Vazkii/Psi#253]
I am using the current Avant 3 Mod Pack (via the curse launcher) that has the current version of PSI at the time of writing this.  Nonsanity suggested looking in the config file to check if the harvest level was on Iron.  It was so I changed it to diamond.  Totally reloaded the game.  

I was able to get obsidian, but alabaster, basalt, immersive engineering, and mechanism blocks still would not break.  Also most of the nether ores and not even nether bricks.

Thanks for the help.
Phil

**Comment by Chaogomu** [comment]
I'll add to this because I've noticed a pattern in the block that will not break.

Any block that just says "pickaxe" in the mining level that waila shows will likely not break with a cad.

Vanilla furnaces are included in the list of blocks that will not break.


---

I'm using the AllTheMods pack which has  Psi-r1.0-39
