### ISSUE TITLE
Idea-Duping... With Consequences

### ISSUE THREAD

**Issue by CTH999** [Vazkii/Psi#373]
Using Eidos Anchor, if you open a chest, take the idem, and go back before you take the item, you can get the item again, and cause a time paradox. A small time paradox could result in you getting teleported to random places near were you are at random times. A larger one could allow you to see the past and present, allowing you to manipulate it with a new spell, but it will quickly drain you energy, killing you at maximum level in a very short amount of time. But, you could use it to watch your base, ore kill someone as they try to enter your base. Larger time paradox's may include something like you never existing, or other bad side effects. The only way to rid you of a time paradox is to destroy all the things you did wrong in time, requiring you to go back in time using the time paradox action thing, and manipulate it to "stop" yourself. Then, it will either cause a large time paradox, or if done correctly, stop your time paradox. But, you no longer have the duped items!
(Or something similar, if you like it)

Thanks

**Comment by yrsegal** [comment]
But eidos only changes your position.

**Comment by CTH999** [comment]
It's just an idea. If it doesn't work, then okay. Would another trick work, or not?

Thanks

**Comment by Darinth** [comment]
To easily abused to duplicate huge numbers of items with no good way that will play with other mods to track things that need 'undone'. Imagine that your put a pouch that is full of some ridiculous number of expensive items. You use this to duplicate the pouch. Maybe some NBT data gets added to the pouch you duplicated so that the game knows the item needs to get destroyed to restore the time line. You take the items out of the pouch and destroy it. Psi will think the timeline was restored, but you got a ridiculous number of free resource. Unfortunately, each mod that makes bags, storage disks, etc... can use it's own proprietary method of storing those items in it's NBT data and I can't imagine a way for this to inter operate with all of them. It's a cool idea... but I can't think of a good way to get it to 'play well' and not be broken when you begin adding other mods to the mix.

**Comment by CTH999** [comment]
Okay, Makes sense to me.

Keep it closed. It is a neat Idea, but is a "little" amusable.

Thanks
