### ISSUE TITLE
Projectile spell entity + Enity Axial Look Direction

### ISSUE THREAD

**Issue by alpharou** [Vazkii/Psi#383]
I've noticed some strange behavior with the Projectile Entity. When you access it's direction it just does random things, in some cases is consistent, other it outputs random vectors all over the place. 

What I'm trying to do: Get a vector starting at the collision's coords, module 1, direction the direction of the spell projectile. 

What I tried to do: I've somewhat circumvented this issue using the caster's look direction, but it's not the same, you could turn fast enough to affect the expected effect.

What I think should happen: Calling Entity axial look/regular look direction should accommodate for the direction the projectile was shot, instead of flipping on the Z axis when using axial look, or returning unpredictable results with the regular direction read.

**Comment by GLugia** [comment]
axial look direction has always given me problems. getting just the look direction of the projectile should do the trick afaik.

**Comment by alpharou** [comment]
Well... I wanted to make a spell to break blocks in a row. Also, the look vector does not work as intended.

**Comment by GLugia** [comment]
as far as I know the only spells that do that are for the psi pickaxe. you can find similar spells on the compendium. otherwise, if you're looking to make your own psigun spell to do this, I haven't found a possible way to do so based on look direction and all that. 

Can we possibly move this to [/r/psispellcompendium](https://www.reddit.com/r/psispellcompendium/) with you stating the full idea of what you want the spell to do? Would be plenty easier to help that way and someone else might tune in to give some tips as well.

**Comment by alpharou** [comment]
I figured it out. It was simple enough when you don't go the focal point's look vector (which is the buggy functionality that stopped me at the moment) I could post it there, but I found out that there are already better versions of this branch mining spell out there. Anyway, this issue was created because of that exact look vector bug and I still think it should behave as I stated in older posts. There's no real way why it should not work. Maybe making the look vector of the projectile be it's movement vector... It makes sense doesn't it? So that it looks where it goes.
