### ISSUE TITLE
Config Options

### ISSUE THREAD

**Issue by gjgfuj** [Vazkii/Psi#40]
I can see lots of potential configuration wise for customizing this mod for use in modpacks.
Some suggestions are:

- [ ] Adjust the amount of psi energy gained per level
- [ ] Adjust the cost of spell parts.
- [ ] Modify levelling order. (probably quite difficult and may be a thing for crafttweaker/custom config system, i understand if it'd be difficult to do quickly.)
- [ ] Adjust the stats of parts.

**Comment by Vazkii** [comment]
I want all these things to stay constant so that spells can be easily shared. If every modpack has completely different stats that becomes a big mess.

**Comment by gjgfuj** [comment]
I'm not entirely sure that allowing the levelling amount to change would
cause any problems at all. I feel like the player has way too much psi at
any point.

I can /see/ a slight problem with allowing the other things to change but I
don't believe it's anything to worry about.

Remember that different modpacks have different balancing requirements.
Of course, its up to you but that's just my thoughts.

**Comment by WolfieWaffle** [comment]
I know this issue is closed, but I agree with gigfuj. I don't think letting users configure things is a problem very often, it should be up to the pack makers to make sure everything is balanced.

**Comment by yrsegal** [comment]
But that interferes with sharing, which is a problem.

**Comment by gjgfuj** [comment]
Considering users don't always have all the abilities enabled in the first
place, (due to the level up system), sharing is typically interfered with
by the mod to itself in the first place. Besides, sharing would still work
even if you could customize the levelups or change stats.

**Comment by yrsegal** [comment]
No, because a spell that works in one modpack with a specific level of psi regen that enables PVP with a certain set of spells might be unsustainable in another, if you could configure it. It creates false expectations.

The unlocking point, the system tells you you haven't learned enough to use a piece you imported that you haven't unlocked yet, but you CAN unlock it. You *can* achieve parity with the other person and import their spell, which you can't do if the stats are different.

**Comment by Vazkii** [comment]
I swear to god @yrsegal, half the emails I get are from you arguing about needless topics. Tone it down.
