### ISSUE TITLE
PSI causes rendering conflicts when used alongside EBWiz which affect other mods as well.

### ISSUE THREAD

**Issue by SirAron111** [Vazkii/Psi#525]
- [x] Make sure you're not reporting something that was just fixed.
- [x] Make sure you're not using an old version of Psi.
- [ ] Make sure you're not using Optifine or GLSL Shaders, if it's a rendering issue.
- [x] Make sure you're using Java 8. Psi will not function in older versions.

SO I recently run into an annoying bug with PSI. If PSI is used alongside EBWiz it triggers a strange rendering issue that affects other mods like Neat. I have no idea what the cause is all I know is that I described the issue in detail in this post https://github.com/Electroblob77/Wizardry/issues/170
I even tried changing around this config option here:
    # Controls whether Psi's shaders are used. If you're using the GLSL Shaders mod and are having graphical troubles with Psi stuff, you may want to turn this off.
    B:"Use Shaders"=true

I tried turning this option to false but that also didn’t help.
This issue is affecting your Mod Neat with the strange combination of mods listed in the other issue I linked. For some reason when EbWiz is installed alongside PSI it starts getting strange visually you can see that by all nameplates turning gray on the neat mod but it also affects other mods that use similar things like the dyn surroundings mob chat that renders above mods the same way neat does. It only happens in combination with PSI so I thought you would be interested in this or maybe you know what the cause could be that PSI triggers this strange behavior.

GZ
SirAron

**Comment by Z-Tunic** [comment]
I wonder if this is why I kept seeing some rendering errors with some mods that I have added. After many MANY tests while narrowing down the mods... this is what I have...

Minecraft: 1.12.2
Forge: 14.23.5.2838

Mods: 4
AutoRegLib-1.3-32
Forgelin-1.8.4
librarianlib-1.12.2-4.19.2-release
Psi-r1.1-76

Mods with Overlays: 5
DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA
OreLib-1.12.2-3.5.2.2
Scannable-MC1.12.2-1.6.3.24
Xaeros_Minimap_1.18.1_Forge_1.12
XaerosWorldMap_1.4.10.1_Forge_1.12

This was tough to pin down mainly because it happens at random upon loading the world/game so you can have everything working fine or the rendering will become bug'd for certian overlays, here's a list of them down below.

-----

Xaero's Minimap with it's very first waypoint becomes gray'd out however the rest of them are unaffected. If Dynamatic Surrounding's : HUD is installed the light overlay will become gray'd out however if Xaero's Minimap Waypoints bug out first then the overlay will work... until you disable the waypoints then the light overlay works.

Scannable's Scanner. When used it creates overlays to locate ores & entities if you have the correct chip installed in it. Now... when used the overlays for Xaero's & DS:H will work correctly however Scannable's overlays will bug out... once scannable's ovelrays disappear then whichever other overlay will once again become broken.

-----

Now for some screenshots....

![](https://cdn.discordapp.com/attachments/377171551155650560/623176700909322251/waypointbug.PNG)
Xaero's Minimap:
Top - The "A" icon is gray'd out yet the other ones are uneffected.
Bottom - Working normally.

![](https://cdn.discordapp.com/attachments/377171551155650560/625026161369677854/dshoverlaybug.PNG)
Dynamatic Surrounding's : HUD
Top - The coloring for the light overlay is gray'd out.
Bottom - The coloring working normally.

![](https://cdn.discordapp.com/attachments/377171551155650560/625028911356706826/scannableoverlaybug.PNG)
Scannable:
Top - You can barely see the overlay, note that DS:H's Light Overlay works as normal when Scannable's Overlay is rendered. Once Scannable's overlay disappears... the Light Overlay will become gray'd out.
Bottom - The Overlay working normally.

-----

Hope this helps with narrowing down the issue. I've tried testing without Forgelin & librarianlib but given the randomness of the issue I couldn't get it to occur so I included those for the time being.
