### ISSUE TITLE
Conjure Light not emiting light to suroundings

### ISSUE THREAD

**Issue by DarkDon** [Vazkii/Psi#646]
Psi version: newest for 1.16.4

# Further Information

1. First step create conjure light spell
2. Second step cast spell
3. light source is created
4. Light source not emitting lightt

What I expected to happen:

emitting light , change of light level

What happened instead:

light source / bulb no change in light level

before light source spell:

[example 1](https://gyazo.com/01aa33b5e6b8a38b6aab71c25f95fbe3)

after spell:

[example 2](https://gyazo.com/6395c1e5517dd514c3f7196f1829971f)

**Comment by VoodooBeard** [comment]
Can confirm. I have experienced the same issue in the ATM6 pack for 1.16.4, with version Psi 1.16-88

**Comment by Mourdraug** [comment]
I tested it in isolated Forge client and got light as expected, however I also don't have light on Valhelsia 3 for 1.16.3 it looks like some other mod might be messing with it. I'd rule out Optifine since it only works on client and serverLight levels are also 0. Anyway, I'd guess that it's not Psi's fault or at leat not entirely.

**Comment by FFormer** [comment]
I came across this issue in DW20's 1.1.2 (also in previous versions) release and did some testing of my own. Because I don't know the first thing about mods I thought it might be because AutoRegLib was not in the DW20 pack so I added it and got the same issue. I then tried a clean install (because I had added 5 mods to the pack myself) and tried it again and the light actually was emitting properly. I then tried adding in the mods I had previously introduced to the pack to see what was causing the issue. The culprit seems to be OptiFine_1.16.4_HD_U_G5.

 I am unsure why OptiFine is doing this but here are some screen shots without OptiFine;
![AfterPlacement(noOptiF)](https://user-images.githubusercontent.com/76502180/102959066-202bd180-44a4-11eb-9d69-8f47000e08b9.png)
![BeforePlacement(noOptiF)](https://user-images.githubusercontent.com/76502180/102959067-20c46800-44a4-11eb-9bad-0040cbb2d6d7.png)

With OptiFine;
![AfterPlacement(OptiFineAdded)](https://user-images.githubusercontent.com/76502180/102959172-71d45c00-44a4-11eb-8c7c-c2185a65f059.png)
![BeforePlacement(OptiFineAdded)](https://user-images.githubusercontent.com/76502180/102959174-726cf280-44a4-11eb-9e85-4fd1540510ca.png)

Note* I have not tested with older versions of Psi or of OptiFine but might be worth a shot. Hope this helps! <3

Version of things;
FTB Presents Direwolf20 1.16-1.1.2
OptiFine_1.16.4_HD_U_G5
Psi 1.16-88

**Comment by gronkki** [comment]
I also (mistakenly, perhaps), reported this bug here, but closed it myself, because, in my case, it was Optifine. However, it is interesting to note that this bug does not occur on my 1.15.2 with Psi and Optifine. The mod author does say in his reporting instructions to make sure you're not using Optifine or GLSL Shaders, if it's a rendering bug. Again, not sure why Optifine would change the actual light level emitted by this block or if that qualifies as a rendering bug, but it does work without Optifine, for me. For me, this shunted me back to 1.15.2. Optifine is a must for my modest gaming laptop.

**Comment by Matazzle** [comment]
Yeah I was having the same issue and was just reported it to the github for Optifine then I stumbled across this github glad to know im not the only having this issue so it isnt just my computer with the issue.

**Comment by Kamefrede** [comment]
fixed in version 91
