### ISSUE TITLE
Formatting errors in json files

### ISSUE THREAD

**Issue by GolendOne1** [Vazkii/Psi#668]
Hello, I am a Chinese player.
I have downloaded the latest psi 1.16-91.
I love this mod, but I found that the Chinese translation doesn't work.
I read the zh_cn.json file and found it has many formatting errors, missing object names, and even some Japanese in it.

Is it not time to update it yet?

Please fix it, I'm looking forward to the Chinese translation of this mod with my friends. We are learning how to assemble magic almost every day now.

BTW, I'm a game developer and I usually use Excel to help me export json files, which ensures correct formatting.  Hope this helps you.

**Comment by Kamefrede** [comment]
Hi, unfortunately none of us at Vazkii's Mods are Chinese translators and instead we rely on volunteers to contribute them to the mod.
While I can't do much to fix it, I think that removing the chinese translation (for now) would be for the best, since if it's poorly translated it might as well be in English.
